CLASS ltcl_does_it_work DEFINITION FINAL FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS.

  PRIVATE SECTION.
    METHODS:
      first_test FOR TESTING RAISING cx_static_check.
ENDCLASS.


CLASS ltcl_does_it_work IMPLEMENTATION.

  METHOD first_test.

  ENDMETHOD.

ENDCLASS.
